### ISSUE TITLE
tensor2tensor

### ISSUE THREAD

**Issue by twairball** [cshanbo/Smooth_BLEU#1]
Hi Justin - I saw that you are an original author of the WMT17 translation code for tensor2tensor. May you send me your email so I can ask you some questions about your thoughts and comparisons of Transformer model on English-Chinese translation?  I can also be reached on twitter @twairball

**Comment by cshanbo** [comment]
Hi there Jerry,
You can email me cshanbo # gmail dot com.
Any suggestions will be welcomed



Thank you.
Shanbo


2017-10-26 9:23 GMT+08:00 Jerry Liu <notifications@github.com>:
